[package]
name = "aeonseed-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
aeonseed-core = { path = "../aeonseed-core" }
bevy = "0.13"

[lib]
path = "src/lib.rs"

[features]
profiling = ["aeonseed-core/profiling"]
